### ISSUE TITLE
Issue with get_config_parameter and worker0.gateway.port

### ISSUE THREAD

**Issue by kiresp** [tableau/server-install-script-samples#17]
I get this error while attempting a 10.4.1 silent install;

...
...
Running: E:\Tableau\Tableau Server\10.4\bin\tabadmin.exe['get', 'worker0.gateway.port']
"tabadmin get worker0.gateway.port" failed; falling back to manual parsing.
get_workgroup_yml with installDir set to: E:\Tableau\Tableau Server
Running: E:\Tableau\Tableau Server\10.4\bin\tabcmd.exe
Failed with output   *** Not authorized
Invalid username or password. (errorCode=16)

I tested manually running E:\Tableau\Tableau Server\10.4\bin\tabadmin.exe get worker0.gateway.port

and it comes back with 80, so it is working.

Not sure why it had to fallback to yaml parsing.

**Comment by ctryphon** [comment]
Did you ever find a resolution to this?   I have the same issue when running 10.5 although the installation completed.

**Comment by dvmorris** [comment]
I am having the same issue, and it's now become a deal breaker for me. I'm going to have to edit the python source code to skip this step. It seems that the python script should just wait a little bit until the tabadmin tool is ready to fetch that config value, but I'm not sure if that's an appropriate solution.

I noticed that in the tabsvc-tabadmin-java.log right around the time the python is trying to fetch this port value from tabadmin, there are some errors related to zookeeper, but I don't know how to resolve those either:

```
2019-01-16 12:37:08.989 -0600 19296@Lenovo-PC ClusterStateManager-ScheduledTask-0-SendThread(0:0:0:0:0:0:0:1:12000) WARN  org.apache.zookeeper.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
```
