### ISSUE TITLE
WaitCondition received failed message: stack rollback

### ISSUE THREAD

**Issue by pashafirdous** [tableau/server-install-script-samples#55]
HI ,

i used the same script for Tableau installation. the stack roolsback with the below error.
kindly asssit in identifying the wait condition issue.

  | 15:5 time | CREATE_FAILED | AWS::CloudFormation::WaitCondition | TableauServerWaitCondition | WaitCondition received failed message: 'Configuration failed.' for uniqueId: i-07c4e744cc0076f68
-- | -- | -- | -- | -- | --
  | Physical ID:arn:aws:cloudformation:us-east-2:803776605671:stack/tablauestack/575dfa70-22e6-11e9-bc1c-0a888d4075c6/TableauServerWaitHandle
  | Client Request Token:Console-CreateStack-9875f6ee-772f-4f1b-9517-f358fc83170d

**Comment by pashafirdous** [comment]
adding content
![image](https://user-images.githubusercontent.com/46807987/51904166-f961df00-23e3-11e9-9c9f-53665b5c3373.png)


The executable file C:\tableau\packages\bin.\tsm.cmd does not exist #C:\tableau is the install directory



[ERROR] Command 4-run-installer ("C:\Program Files\Python36\python.exe" SilentInstaller.py install --secretsFile c:\tabsetup\secrets.json --registrationFile c:\tabsetup\registration.json --configFile c:\tabsetup\config.json --installDir d:\tableau c:\tabsetup\tableau-server-webapp-installer.exe  > c:\tabsetup\tsm_installer-output.txt 2>&1) failed
2019-01-29 10:46:17,911 [DEBUG] Command 4-run-installer output: 
2019-01-29 10:46:17,911 [ERROR] Error encountered during build of config: Command 4-run-installer failed
Traceback (most recent call last):
  File "cfnbootstrap\construction.pyc", line 544, in run_config
  File "cfnbootstrap\construction.pyc", line 138, in run_commands
  File "cfnbootstrap\command_tool.pyc", line 117, in apply
ToolError: Command 4-run-installer failed
2019-01-29 10:46:17,911 [ERROR] -----------------------BUILD FAILED!------------------------
2019-01-29 10:46:17,911 [ERROR] Unhandled exception during build: Command 4-run-installer failed
Traceback (most recent call last):

**Comment by pashafirdous** [comment]
this is continuation for above error...

Error: **The executable file c:\tableau\packages\bin.\tsm.cmd does not exist**

the scripts initiates installation of Tableau server but fails at the the above error. this gives a fail signal to the CF template.

looking for tableau installation on windows - Cloud formation.

**Comment by pashafirdous** [comment]
tsmoutput.....#########
Authentication error. Incorrect username or password, or username not member of administrative group?
Tabadmin exited with code 1
######
cfn-init-cmd...
2019-01-30 19:22:06,559 P2272 [INFO] Command 4-run-installer
2019-01-30 19:26:37,690 P2272 [ERROR] Exited with error code 4
###########

cfn-init
2019-01-30 19:26:37,690 [ERROR] Error encountered during build of config: Command 4-run-installer failed
Traceback (most recent call last):
  File "cfnbootstrap\construction.pyc", line 544, in run_config
  File "cfnbootstrap\construction.pyc", line 138, in run_commands
  File "cfnbootstrap\command_tool.pyc", line 117, in apply
ToolError: Command 4-run-installer failed
2019-01-30 19:26:37,690 [ERROR] -----------------------BUILD FAILED!------------------------
2019-01-30 19:26:37,690 [ERROR] Unhandled exception during build: Command 4-run-installer failed
Traceback (most recent call last):
  File "cfn-init", line 171, in <module>
  File "cfnbootstrap\construction.pyc", line 129, in build
  File "cfnbootstrap\construction.pyc", line 530, in build
